version: '3.9'
services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_DB: ecommerce_docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce-net

  app:
    build: .
    container_name: nestapp
    restart: always
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - postgresdb
    networks:
      - ecommerce-net

volumes:
  pgdata:

networks:
  ecommerce-net:
